# Generated by Django 5.2.10 on 2026-01-27 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.CharField(choices=[('AcademicBackground', 'AcademicBackground'), ('StudyGoal', 'StudyGoal'), ('Budget', 'Budget'), ('ExamsAndReadiness', 'ExamsAndReadiness'), ('Completed', 'Completed')], default='AcademicBackground', max_length=50),
        ),
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=100)),
                ('degree_major', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('gpa', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_background', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_range', models.CharField(max_length=100)),
                ('funding_plan', models.CharField(choices=[('Self-funded', 'Self-funded'), ('Scholarship-dependent', 'Scholarship-dependent'), ('Loan-dependent', 'Loan-dependent')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamsAndReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ielts_toefl_status', models.CharField(blank=True, max_length=100, null=True)),
                ('gre_gmat_status', models.CharField(blank=True, max_length=100, null=True)),
                ('sop_status', models.CharField(blank=True, choices=[('Not started', 'Not started'), ('Draft', 'Draft'), ('Ready', 'Ready')], max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exams_readiness', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intended_degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=255)),
                ('target_intake', models.CharField(max_length=50)),
                ('preferred_countries', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned User')),
            ],
        ),
    ]
