# Generated by Django 5.2.10 on 2026-01-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_onboarding_step_academicbackground_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('PROFILE', 'Profile Building'), ('UNIVERSITY', 'University Shortlisting'), ('APPLICATION', 'Application Process'), ('PERSONAL', 'Personal')], default='PERSONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
