# Generated by Django 5.2.10 on 2026-01-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_created_at_task_is_completed_task_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsandreadiness',
            name='gre_gmat_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examsandreadiness',
            name='ielts_toefl_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
