# Generated by Django 5.2.10 on 2026-01-28 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_examsandreadiness_gre_gmat_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Dream', 'Dream'), ('Target', 'Target'), ('Safe', 'Safe')], max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_universities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
