# Generated by Django 5.2.10 on 2026-01-29 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shortlisteduniversity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('strength_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_cache', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
