# Generated by Django 5.2.10 on 2026-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chatsession_chatmessage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_visited_explore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_visited_shortlist',
            field=models.BooleanField(default=False),
        ),
    ]
